name: pr-list-notification

# on:
#   workflow_dispatch:  # 수동으로 워크플로우 트리거

on:
  schedule:
    # - cron: '30 0 * * 1-5' # 매주 월요일부터 금요일까지 KST 오전 8시 30분에 실행
    - cron: '30 23 * * 0-4' # 매주 월요일부터 금요일까지 KST 오전 8시 30분에 실행
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run main.py
        run: |
          python main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
